### ISSUE TITLE
Normalization when co-training

### ISSUE THREAD

**Issue by QazyBi** [droid-dataset/droid#14]
Hello! I am preparing to apply co-training using my own dataset alongside DROID, and I have a question about the normalization strategy used for:
1. In-domain demonstrations
2. Open X-Embodiment dataset

Could you confirm whether each dataset should be normalized separately for co-training? Thank you for your assistance!

**Comment by kpertsch** [comment]
Hi!
It's usually a good default to normalize each dataset separately, just make sure to use the correct unnorm stats at inference time!
