### ISSUE TITLE
Missing language instructions

### ISSUE THREAD

**Issue by Jay-Ye** [droid-dataset/droid#3]
Hi, congrats for this great work. 
I noticed that there are a significant of episodes that don't have any language instructions as shown in the following screenshot.
Please let me know if I missed anything.
![image](https://github.com/droid-dataset/droid/assets/52844723/897ac7dd-27ce-42ee-a943-97e0b6a90b2a)

**Comment by kpertsch** [comment]
Hi!
Thanks for the interest in DROID! We're still waiting on our annotation provider to finish the full annotation -- at the moment 50k of the 76k success trajectories are annotated and we did not want to delay the release by another few weeks. We will upload the dataset with all annotations as soon as they are completed by the annotation provider, which we expect to be the case in a few weeks, but hope that the 50k annotated trajectories are useful in the meantime!

**Comment by Jay-Ye** [comment]
Thanks for the update. I appreciate your efforts in making such a high-quality robotic dataset open source.

**Comment by tlpss** [comment]
> Hey [@kpertsch](https://github.com/kpertsch), is the current dataset updated with all the language instructions? I still find that significant amount of episodes are missing the language instruction. Thank you!! Oops, it is there on hugging face, just saw the update, sorry!!

The language instructions are available [here](https://huggingface.co/KarlP/droid)
