### ISSUE TITLE
How to filter out a subset of a dataset that contains a portion of tasks and is around 100GB in size

### ISSUE THREAD

**Issue by StarCycle** [droid-dataset/droid#7]
Hello,

Thank you for sharing the dataset! The full RLDS dataset is a little large (1.7TB), while the example dataset is too small with only 100 episodes. 

- What kind of task does the example dataset (100 episodes) contain?
- How to filter out a subset of a dataset that contains a portion of tasks and is around 100GB in size? This will be easier for beginners.
- If my understanding is correct, your [colab notebook](https://colab.research.google.com/drive/1b4PPH4XGht4Jve2xPKMCh-AXXAQziNQa?usp=sharing#scrollTo=fJwXAbqgcLI-) does not need to download the dataset. 
```
ds = tfds.load("droid_100", data_dir="gs://gresearch/robotics", split="train")
for episode in ds.shuffle(10, seed=0).take(1):
```
just loads samples from Google storage bucket if they are needed (like Web Dataset), right?

I am training on Vast.ai, where the maximum disk space is around 2TB. Using the full RLDS dataset is not convenient for me...

Best,
StarCycle

**Comment by kpertsch** [comment]
Thanks for your interest in our dataset!
The 100 episodes are sampled randomly from the full dataset so they contain randomly sampled tasks (feel free to just inspect them, it's only 2GB)

For downloading a subset -- this is not something officially supported by TFDS and not something I have tried, but I think you can just download the first N shards of the dataset (ie check out the TFDS data folder and you can see that it has 2048 shard files). In your case you'd want to download the first 1.7TB / 2048 * 100 ~= 85 shards. Then when you load the dataset, specify the `split` as a conservative subsplit of the train dataset, eg in your case `split=train[:5%]` and see whether this works. Note that you also need to download the `dataset_info.json` and `features.json` files from the directory for this to work.

Re web dataset: please don't use the direct streaming from bucket for training -- it will make your training slow and will incur huge egress costs for us on the cloud bucket. It is better if you download the portion of the dataset you want locally first.

**Comment by StarCycle** [comment]
Thanks!

I will come back to this issue if I meet problems about it!

**Comment by HongruiTang** [comment]
Hi @kpertsch, thank you so much for your reply! I have a follow-up question on it. I wonder if I can download demos of a specific task (eg. pick and place) from DROID. I saw the demos are categorized into different tasks in the [DROID Dataset Visualizer](https://droid-dataset.github.io/visualizer/) but I didn't find such fields in the episode information. Could you share how you categorized the demos? 

Thank you!

**Comment by zillur01** [comment]
@HongruiTang have you figure it out?
